In [2]:
import numpy as np
import time

In [3]:
a = np.zeros(4)
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,))
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4) 
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.6324133  0.34852445 0.4488638  0.9006124 ], a shape = (4,), a data type = float64


In [4]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.30055821 0.08553216 0.43994953 0.68353981], a shape = (4,), a data type = float64


In [ ]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

In [10]:
a = np.arange(10)
print(a)
#accessing an element 
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

#accessing the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

# indexes must be withing the range of the vector

try:
    c = a[10]
except Exception as e:
    print("The error :" ,e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error : index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [17]:
a = np.arange(10)
print(f"a        = {a}")

# accessing 5 consecutive elements (start : stop : step)
c = a[2 : 7 : 1]
print("a[2:7:1] = ", c) # prints till stop - 1

# accessing 3 elements by step two

c = a[2 : 7 : 2]
print("a[2:7:2] = ", c)

# access all elements index 3 and above

c = a[3 : ]
print("a[3:]    = ", c)

# access all elements below index 3

c = a[: 3]
print("a[:3]    = ", c)

# access all elements

c = a[:]
print(f"a[:]     = {c}")

a        = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     = [0 1 2 3 4 5 6 7 8 9]


### Single vector operations

In [18]:
a = np.array([1, 2, 3, 4])
print(f"a           : {a}")

# negate all elements 

b = -a
print(f"b           : {b}")

#sum all elements of a, return a scalar

b = np.sum(a)
print(f"b = np.sum(a): {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a ** 2
print(f"b = a**2      : {b}")

a           : [1 2 3 4]
b           : [-1 -2 -3 -4]
b = np.sum(a): 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ c_i = a_i + b_i $$

Of course, for this to work correctly, the vectors must be of the same size:

In [21]:
a = np.array([1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])

print(f"Binary operators work element wise: {a + b}")

#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message is:")
    print(e)

Binary operators work element wise: [0 0 6 8]
The error message is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

In [22]:
a = np.array([1, 2, 3, 4])

# multiply by a scalar 

b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### Vector Vector dot product
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

Let's implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

In [23]:
def own_dot(a, b):
    x = 0
    for i in range (a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {own_dot(a, b)}")

my_dot(a, b) = 24


In [26]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

c = np.dot(a, b)

print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


<a name="toc_40015_3.4.7"></a>
### The Need for Speed: vector vs for loop
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:

In [27]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time() # start time
c = np.dot(a, b)
toc = time.time() #end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = own_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 10.0207 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 5685.5350 ms 


<a name="toc_40015_4.3"></a>
## Matrix Creation
The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples


In [30]:
a = np.zeros((1,5))
print(f"a shape = {a.shape}, a = {a}")   

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((5,5))
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.04997798]]
a shape = (5, 5), a = [[0.77390955 0.93782363 0.5792328  0.53516563 0.80204309]
 [0.24814448 0.59096694 0.32950282 0.98797985 0.86846315]
 [0.16452144 0.80277814 0.02503441 0.89766393 0.41783454]
 [0.53671084 0.19721356 0.26810967 0.5669563  0.36607953]
 [0.12254939 0.41590761 0.83186916 0.49357909 0.90762403]]


In [ ]:
# Manual data entry

# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

### Indexing

Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

In [34]:
a = np.arange(6).reshape(-1, 2) # -1 in reshape() tells NumPy to automatically calculate that dimension 
print(f"a.shape: {a.shape}, \na= {a}")

# access an element
print(f"\na[2,0].shape  : {a[2, 0].shape}, a[2, 0] = {a[2, 0]},   type(a[2, 0]) = {type(a[2, 0])} ")

# access a row
print(f"a[2].shape  : {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])} ")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape  : (), a[2, 0] = 4,   type(a[2, 0]) = <class 'numpy.int64'> 
a[2].shape  : (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'> 


**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.


<a name="toc_40015_4.4.2"></a>
### Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [42]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n {a}")

# access 5 consecutive elements 
print(f"a[0, 2:7:1] = {a[0, 2:7:1]}, a[0, 2:7:1].shape = {a[0, 2:7:1].shape}")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements 
print(f"a[:, :] = \n {a[:, :]}, a[:, :].shape = {a[:, :].shape}")


# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] = [2 3 4 5 6], a[0, 2:7:1].shape = (5,)
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:, :] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]], a[:, :].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
